/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crud.pmb;

import java.sql.*;
import javax.swing.*;;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Fikri Ikmalul
 */
public class menupanel extends javax.swing.JFrame {
    
    private Connection koneksi;

    /**
     * Creates new form menupanel
     */
    public menupanel() {
        initComponents();
        KoneksiDatabase();
        TampilData();
        setLocationRelativeTo(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpframe = new javax.swing.JPanel();
        jpmenu = new javax.swing.JPanel();
        bhome = new javax.swing.JButton();
        bdaftar = new javax.swing.JButton();
        bdata = new javax.swing.JButton();
        bkeluar = new javax.swing.JButton();
        jpisi = new javax.swing.JPanel();
        jphome = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jpdaftar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnamalengkap = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txttempatlahir = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txttanggallahir = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        rblaki = new javax.swing.JRadioButton();
        rbperempuan = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        txtkewarganegaraan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtnik = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtnotelepon = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtasalsekolah = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtalamat = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtkodepos = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtprovinsi = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtkabkota = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtkecamatan = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        cbagama = new javax.swing.JComboBox<>();
        cbpilihan1 = new javax.swing.JComboBox<>();
        cbpilihan2 = new javax.swing.JComboBox<>();
        cbpilihan3 = new javax.swing.JComboBox<>();
        bsimpan = new javax.swing.JButton();
        bbatal = new javax.swing.JButton();
        bubah = new javax.swing.JButton();
        jpdata = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblmahasiswabaru = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        bhapus = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();
        bcari = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpframe.setBackground(new java.awt.Color(0, 153, 153));
        jpframe.setPreferredSize(new java.awt.Dimension(800, 800));

        jpmenu.setBackground(new java.awt.Color(0, 102, 102));

        bhome.setText("HOME");
        bhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhomeActionPerformed(evt);
            }
        });

        bdaftar.setText("DAFTAR");
        bdaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdaftarActionPerformed(evt);
            }
        });

        bdata.setText("DATA");
        bdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdataActionPerformed(evt);
            }
        });

        bkeluar.setText("KELUAR");
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpmenuLayout = new javax.swing.GroupLayout(jpmenu);
        jpmenu.setLayout(jpmenuLayout);
        jpmenuLayout.setHorizontalGroup(
            jpmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpmenuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jpmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bdata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bhome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bdaftar, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addComponent(bkeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jpmenuLayout.setVerticalGroup(
            jpmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpmenuLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(bhome)
                .addGap(57, 57, 57)
                .addComponent(bdaftar)
                .addGap(52, 52, 52)
                .addComponent(bdata)
                .addGap(56, 56, 56)
                .addComponent(bkeluar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpisi.setBackground(new java.awt.Color(0, 102, 102));

        jphome.setBackground(new java.awt.Color(0, 204, 204));
        jphome.setPreferredSize(new java.awt.Dimension(558, 700));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/1.jpg"))); // NOI18N

        javax.swing.GroupLayout jphomeLayout = new javax.swing.GroupLayout(jphome);
        jphome.setLayout(jphomeLayout);
        jphomeLayout.setHorizontalGroup(
            jphomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jphomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                .addContainerGap())
        );
        jphomeLayout.setVerticalGroup(
            jphomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jphomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        jpdaftar.setBackground(new java.awt.Color(0, 204, 204));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FORM PENDAFTARAN MAHASISWA BARU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(79, 79, 79))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DATA DIRI");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nama Lengkap");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tempat Lahir");

        txttempatlahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttempatlahirActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tanggal Lahir");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Jenis Kelamin");

        rblaki.setForeground(new java.awt.Color(255, 255, 255));
        rblaki.setText("Laki-laki");

        rbperempuan.setForeground(new java.awt.Color(255, 255, 255));
        rbperempuan.setText("Perempuan");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Kewarganegaraan");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Agama");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nomor Identitas (NIK)");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("No Telepon");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Asal Sekolah");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("TEMPAT TINGGAL");

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Alamat");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Email");

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Kode Pos");

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Provinsi");

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Kab/Kota");

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Kecamatan");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("PILIHAN PROGRAM STUDI & KELAS");

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Pilihan Program Studi 1");

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Pilihan Program Studi 2");

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Pilihan Kelas");

        cbagama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- SILAHKAN PILIH --", "Islam", "Kristen", "Katholik", "Hindu", "Budha" }));

        cbpilihan1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- SILAHKAN PILIH --", "Teknik Sipil", "Teknik Informatika", "Manajemen", "Akuntansi", "PBSI", "PGSD", "Agribisnis", "Ilmu dan Teknologi Pangan", "Ilmu Gizi", "Farmasi" }));

        cbpilihan2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- SILAHKAN PILIH --", "Teknik Sipil", "Teknik Informatika", "Manajemen", "Akuntansi", "PBSI", "PGSD", "Agribisnis", "Ilmu dan Teknologi Pangan", "Ilmu Gizi", "Farmasi" }));

        cbpilihan3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- SILAHKAN PILIH --", "Reguler", "Karyawan" }));

        bsimpan.setText("SIMPAN");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        bbatal.setText("BATAL");
        bbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalActionPerformed(evt);
            }
        });

        bubah.setText("UBAH");
        bubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtalamat, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(txtnamalengkap, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(txttempatlahir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGap(27, 27, 27)
                                                        .addComponent(jLabel7))
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGap(17, 17, 17)
                                                        .addComponent(txttanggallahir, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel10))))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(rblaki)
                                                .addGap(18, 18, 18)
                                                .addComponent(rbperempuan))
                                            .addComponent(jLabel8)
                                            .addComponent(txtkewarganegaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbagama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(5, 5, 5)))
                                .addComponent(jLabel16))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtprovinsi, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(txtkabkota))))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17)
                            .addComponent(jLabel11)
                            .addComponent(txtnik)
                            .addComponent(jLabel12)
                            .addComponent(txtnotelepon)
                            .addComponent(jLabel13)
                            .addComponent(txtemail)
                            .addComponent(jLabel14)
                            .addComponent(txtasalsekolah)
                            .addComponent(txtkodepos)
                            .addComponent(jLabel20)
                            .addComponent(txtkecamatan, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bsimpan)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbpilihan1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(cbpilihan2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbpilihan3, 0, 1, Short.MAX_VALUE)
                            .addComponent(jLabel24)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(bbatal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bubah)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnamalengkap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttempatlahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttanggallahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnotelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rblaki)
                    .addComponent(rbperempuan)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtkewarganegaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtasalsekolah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbagama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtkodepos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(jLabel20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtkecamatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtprovinsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtkabkota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbpilihan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbpilihan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbpilihan3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bsimpan)
                    .addComponent(bbatal)
                    .addComponent(bubah))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jpdaftarLayout = new javax.swing.GroupLayout(jpdaftar);
        jpdaftar.setLayout(jpdaftarLayout);
        jpdaftarLayout.setHorizontalGroup(
            jpdaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpdaftarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpdaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpdaftarLayout.setVerticalGroup(
            jpdaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpdaftarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpdata.setBackground(new java.awt.Color(0, 102, 102));
        jpdata.setPreferredSize(new java.awt.Dimension(558, 652));

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(546, 634));

        tblmahasiswabaru.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tblmahasiswabaru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIK", "Nama Lengkap", "Tempat Lahir", "Tanggal Lahir", "Jenis Kelamin", "Kewarganegaraan", "Agama", "No Telepon", "Email", "Asal Sekolah", "Alamat", "Kode Pos", "Provinsi", "Kab/Kota", "Kecamatan", "Pilihan Prodi 1", "Pilihan Prodi 2", "Pilihan Kelas"
            }
        ));
        tblmahasiswabaru.setAutoResizeMode(0);
        tblmahasiswabaru.setAutoscrolls(false);
        tblmahasiswabaru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblmahasiswabaruMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblmahasiswabaru);

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setForeground(new java.awt.Color(0, 153, 153));
        jPanel4.setPreferredSize(new java.awt.Dimension(558, 70));

        bhapus.setText("HAPUS");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcariKeyReleased(evt);
            }
        });

        bcari.setText("CARI");
        bcari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bcariMouseClicked(evt);
            }
        });
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bcari))
                    .addComponent(bhapus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bcari, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtcari, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bhapus)
                .addGap(12, 12, 12))
        );

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA MAHASISWA BARU");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(116, 116, 116))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpdataLayout = new javax.swing.GroupLayout(jpdata);
        jpdata.setLayout(jpdataLayout);
        jpdataLayout.setHorizontalGroup(
            jpdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpdataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpdataLayout.setVerticalGroup(
            jpdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpdataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jpisiLayout = new javax.swing.GroupLayout(jpisi);
        jpisi.setLayout(jpisiLayout);
        jpisiLayout.setHorizontalGroup(
            jpisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jpisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpisiLayout.createSequentialGroup()
                    .addComponent(jphome, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                    .addGap(0, 116, Short.MAX_VALUE)))
            .addGroup(jpisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpisiLayout.createSequentialGroup()
                    .addComponent(jpdaftar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(99, 99, 99)))
            .addGroup(jpisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpdata, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE))
        );
        jpisiLayout.setVerticalGroup(
            jpisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 956, Short.MAX_VALUE)
            .addGroup(jpisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpisiLayout.createSequentialGroup()
                    .addComponent(jphome, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                    .addGap(0, 156, Short.MAX_VALUE)))
            .addGroup(jpisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpisiLayout.createSequentialGroup()
                    .addComponent(jpdaftar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jpisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpdata, javax.swing.GroupLayout.DEFAULT_SIZE, 956, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpframeLayout = new javax.swing.GroupLayout(jpframe);
        jpframe.setLayout(jpframeLayout);
        jpframeLayout.setHorizontalGroup(
            jpframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpframeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpframeLayout.setVerticalGroup(
            jpframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpframeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpframe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpframe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhomeActionPerformed
        // TODO add your handling code here:
        jpisi.removeAll();
        jpisi.repaint();
        jpisi.revalidate();
        
        //menambahkan panel
        jpisi.add(jphome);
        jpisi.repaint();
        jpisi.revalidate();
    }//GEN-LAST:event_bhomeActionPerformed

    private void bdaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdaftarActionPerformed
        // TODO add your handling code here:
        jpisi.removeAll();
        jpisi.repaint();
        jpisi.revalidate();
        
        //menambahkan panel
        jpisi.add(jpdaftar);
        jpisi.repaint();
        jpisi.revalidate();
    }//GEN-LAST:event_bdaftarActionPerformed

    private void bdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdataActionPerformed
        // TODO add your handling code here:
        jpisi.removeAll();
        jpisi.repaint();
        jpisi.revalidate();
        
        //menambahkan panel
        jpisi.add(jpdata);
        jpisi.repaint();
        jpisi.revalidate();
    }//GEN-LAST:event_bdataActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Ingin Keluar?", "Terima Kasih Atas Perhatiannya", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_bkeluarActionPerformed

    private void txttempatlahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttempatlahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttempatlahirActionPerformed

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
        // TODO add your handling code here:
        txtnik.setText("");
        txtnamalengkap.setText("");
        txttempatlahir.setText("");
        txttanggallahir.setText("");
        txtkewarganegaraan.setText("");
        cbagama.setSelectedIndex(-0);
        txtnotelepon.setText("");
        txtemail.setText("");
        txtasalsekolah.setText("");
        txtalamat.setText("");
        txtkodepos.setText("");
        txtprovinsi.setText("");
        txtkabkota.setText("");
        txtkecamatan.setText("");
        cbpilihan1.setSelectedIndex(-0);
        cbpilihan2.setSelectedIndex(-0);
        cbpilihan3.setSelectedIndex(-0);
        txtnik.requestFocus();
    }//GEN-LAST:event_bbatalActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        // TODO add your handling code here:
        String nik = txtnik.getText();
        String namalengkap = txtnamalengkap.getText();
        String tempatlahir = txttempatlahir.getText();
        String tanggallahir = txttanggallahir.getText();
        String jeniskelamin = null;
        if (rblaki.isSelected()) {
            jeniskelamin = "Laki-Laki";
        } else if (rbperempuan.isSelected()) {
            jeniskelamin = "Perempuan";
        }
        String kewarganegaraan = txtkewarganegaraan.getText();
        String agama = (String) cbagama.getSelectedItem();
        String notelepon = txtnotelepon.getText();
        String email = txtemail.getText();
        String asalsekolah = txtasalsekolah.getText();
        String alamat = txtalamat.getText();
        String kodepos = txtkodepos.getText();
        String provinsi = txtprovinsi.getText();
        String kabkota = txtkabkota.getText();
        String kecamatan = txtkecamatan.getText();
        String pilihan1 = (String) cbpilihan1.getSelectedItem();
        String pilihan2 = (String) cbpilihan2.getSelectedItem();
        String pilihan3 = (String) cbpilihan3.getSelectedItem();
        if (txtnik.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Mohon Masukkan Data untuk di Input", "PERHATIAN", JOptionPane.WARNING_MESSAGE);
        } else {
             try {
                 java.sql.Statement stat = koneksi.createStatement();
                 ResultSet data = stat.executeQuery("SELECT * FROM mahasiswabaru WHERE NIK ='" + txtnik.getText() + "'");
                 if (data.next()) {
                     JOptionPane.showMessageDialog(null, "NIK Sudah Ada", "PERHATIAN", JOptionPane.WARNING_MESSAGE);
                     txtnik.requestFocus();
                 } else {
                    String sql = "INSERT INTO mahasiswabaru VALUES('" + nik + "'"
                           + ",'" + namalengkap + "'"
                           + ",'" + tempatlahir + "'"
                           + ",'" + tanggallahir + "'"
                           + ",'" + jeniskelamin + "'"
                           + ",'" + kewarganegaraan + "'"
                           + ",'" + agama + "'"
                           + ",'" + notelepon + "'"
                           + ",'" + email + "'"
                           + ",'" + asalsekolah + "'"
                           + ",'" + alamat + "'"
                           + ",'" + kodepos + "'"
                           + ",'" + provinsi + "'"
                           + ",'" + kabkota + "'"
                           + ",'" + kecamatan + "'"
                           + ",'" + pilihan1 + "'"
                           + ",'" + pilihan2 + "'"
                           + ",'" + pilihan3 + "')";
                    stat.executeUpdate(sql);
                    txtnik.setText("");
                    txtnamalengkap.setText("");
                    txttempatlahir.setText("");
                    txttanggallahir.setText("");
                    txtkewarganegaraan.setText("");
                    cbagama.setSelectedIndex(-0);
                    txtnotelepon.setText("");
                    txtemail.setText("");
                    txtasalsekolah.setText("");
                    txtalamat.setText("");
                    txtkodepos.setText("");
                    txtprovinsi.setText("");
                    txtkabkota.setText("");
                    txtkecamatan.setText("");
                    cbpilihan1.setSelectedIndex(-0);
                    cbpilihan2.setSelectedIndex(-0);
                    cbpilihan3.setSelectedIndex(-0);
                    txtnik.requestFocus();
                    JOptionPane.showMessageDialog(null, "Data Berhasil Di Simpan", "SUKSES", JOptionPane.INFORMATION_MESSAGE);
                    TampilData();
                 }
                    stat.close();
                } catch (Exception exc) {
                    System.err.println("Terjadi Kesalahan :" + exc);
             }
        } 
    }//GEN-LAST:event_bsimpanActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin menghapus data ini?", "Konfirmasi Dialog", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            String sql = "DELETE FROM mahasiswabaru WHERE NIK='" + txtnik.getText().trim() + "'";
            try {
                 Statement stat = koneksi.createStatement();
                 stat.executeUpdate(sql);
                 JOptionPane.showMessageDialog(null, "Data Berhasil di Hapus", "Hapus Data", JOptionPane.INFORMATION_MESSAGE);
                 stat.close();
                 txtnik.setText("");
                 txtnamalengkap.setText("");
                 txttempatlahir.setText("");
                 txttanggallahir.setText("");
                 txtkewarganegaraan.setText("");
                 cbagama.setSelectedIndex(-0);
                 txtnotelepon.setText("");
                 txtemail.setText("");
                 txtasalsekolah.setText("");
                 txtalamat.setText("");
                 txtkodepos.setText("");
                 txtprovinsi.setText("");
                 txtkabkota.setText("");
                 txtkecamatan.setText("");
                 cbpilihan1.setSelectedIndex(-0);
                 cbpilihan2.setSelectedIndex(-0);
                 cbpilihan3.setSelectedIndex(-0);
                 txtnik.requestFocus();
                 TampilData();
              } catch (SQLException exc) {
                  System.err.println(sql);
                  System.err.println("Error : " + exc);
              }
        }                   
    }//GEN-LAST:event_bhapusActionPerformed

    private void bubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin mengubah data ini?", "Konfirmasi Dialog", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
        String jeniskelamin = null;
        if (rblaki.isSelected()) {
            jeniskelamin = "Laki-Laki";
        } else if (rbperempuan.isSelected()) {
            jeniskelamin = "Perempuan";
        }
        String sql = "update mahasiswabaru set nama_lengkap='" + txtnamalengkap.getText()
                + "',tempat_lahir='" + txttempatlahir.getText()
                + "',tanggal_lahir='" + txttanggallahir.getText()
                + "',jenis_kelamin='" + jeniskelamin
                + "',kewarganegaraan='" + txtkewarganegaraan.getText()
                + "',agama='" + cbagama.getSelectedItem()
                + "',no_telepon='" + txtnotelepon.getText()
                + "',email='" + txtemail.getText()
                + "',asal_sekolah='" + txtasalsekolah.getText()
                + "',alamat='" + txtalamat.getText()
                + "',kode_pos='" + txtkodepos.getText()
                + "',provinsi='" + txtprovinsi.getText()
                + "',kabkota='" + txtkabkota.getText()
                + "',kecamatan='" + txtkecamatan.getText()
                + "',prodi_satu='" + cbpilihan1.getSelectedItem()
                + "',prodi_dua='" + cbpilihan2.getSelectedItem()
                + "',pilih_kelas='" + cbpilihan3.getSelectedItem()
                + "'where NIK='" + txtnik.getText().trim() + "'";
        if (txtnik.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Data Masih Kosong!", "Ubah Data", JOptionPane.WARNING_MESSAGE);
            txtnik.requestFocus();
        } else {
            try {
                 Statement stat = koneksi.createStatement();
                 stat.executeUpdate(sql);
                 JOptionPane.showMessageDialog(null, "Data Berhasil di Ubah", "Ubah Data", JOptionPane.INFORMATION_MESSAGE);
                 stat.close();
                 txtnik.requestFocus();
                 TampilData();
            } catch (Exception exc) {
                System.err.println("Error :" + exc);
            }
          }
        }                 
    }//GEN-LAST:event_bubahActionPerformed

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
        // TODO add your handling code here:
        try {
            java.sql.Statement stat = koneksi.createStatement();
            ResultSet data = stat.executeQuery("SELECT * from mahasiswabaru where NIK like '%"+txtcari.getText()+"%'" + "or pilih_kelas like '%"+txtcari.getText()+"%'");
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("NIK");
            model.addColumn("Nama Lengkap");
            model.addColumn("Tempat Lahir");
            model.addColumn("Tanggal Lahir");
            model.addColumn("Jenis Kelamin");
            model.addColumn("Kewarganegaraan");
            model.addColumn("Agama");
            model.addColumn("No Telepon");
            model.addColumn("Email");
            model.addColumn("Asal Sekolah");
            model.addColumn("Alamat");
            model.addColumn("Kode Pos");
            model.addColumn("Provinsi");
            model.addColumn("Kab/Kota");
            model.addColumn("Kecamatan");
            model.addColumn("Pilihan Prodi 1");
            model.addColumn("Pilihan Prodi 2");
            model.addColumn("Pilihan Kelas");
            tblmahasiswabaru.setModel(model);
            
            int no = 1;
            while (data.next()) {
                model.addRow(new Object[]{
                        data.getString("NIK"),
                        data.getString("nama_lengkap"),
                        data.getString("tempat_lahir"),
                        data.getString("tanggal_lahir"),
                        data.getString("jenis_kelamin"),
                        data.getString("kewarganegaraan"),
                        data.getString("agama"),
                        data.getString("no_telepon"),
                        data.getString("email"),
                        data.getString("asal_sekolah"),
                        data.getString("alamat"),
                        data.getString("kode_pos"),
                        data.getString("provinsi"),
                        data.getString("kabkota"),
                        data.getString("kecamatan"),
                        data.getString("prodi_satu"),
                        data.getString("prodi_dua"),
                        data.getString("pilih_kelas")
                });
                tblmahasiswabaru.setModel(model);
                no++;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan", "WARNING", JOptionPane.WARNING_MESSAGE);
        }
            
    }//GEN-LAST:event_bcariActionPerformed

    private void txtcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariKeyReleased

    private void bcariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcariMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bcariMouseClicked

    private void tblmahasiswabaruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblmahasiswabaruMouseClicked
        // TODO add your handling code here:
        int baris = tblmahasiswabaru.getSelectedRow();
        if (baris != -1) {
            txtnik.setText(tblmahasiswabaru.getValueAt(baris, 0).toString());
            txtnamalengkap.setText(tblmahasiswabaru.getValueAt(baris, 1).toString());
            txttempatlahir.setText(tblmahasiswabaru.getValueAt(baris, 2).toString());
            txttanggallahir.setText(tblmahasiswabaru.getValueAt(baris, 3).toString());
            if ("Laki-Laki".equals(tblmahasiswabaru.getValueAt(baris, 4).toString())) {
                rblaki.setSelected(true);
            } else {
                rbperempuan.setSelected(true);
                }
            }
            txtkewarganegaraan.setText(tblmahasiswabaru.getValueAt(baris, 5).toString());
            cbagama.setSelectedItem(tblmahasiswabaru.getValueAt(baris, 6).toString());
            txtnotelepon.setText(tblmahasiswabaru.getValueAt(baris, 7).toString());
            txtemail.setText(tblmahasiswabaru.getValueAt(baris, 8).toString());
            txtasalsekolah.setText(tblmahasiswabaru.getValueAt(baris, 9).toString());
            txtalamat.setText(tblmahasiswabaru.getValueAt(baris, 10).toString());
            txtkodepos.setText(tblmahasiswabaru.getValueAt(baris, 11).toString());
            txtprovinsi.setText(tblmahasiswabaru.getValueAt(baris, 12).toString());
            txtkabkota.setText(tblmahasiswabaru.getValueAt(baris, 13).toString());
            txtkecamatan.setText(tblmahasiswabaru.getValueAt(baris, 14).toString());
            cbpilihan1.setSelectedItem(tblmahasiswabaru.getValueAt(baris, 15).toString());
            cbpilihan2.setSelectedItem(tblmahasiswabaru.getValueAt(baris, 16).toString());
            cbpilihan3.setSelectedItem(tblmahasiswabaru.getValueAt(baris, 17).toString());
        
    }//GEN-LAST:event_tblmahasiswabaruMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menupanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menupanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menupanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menupanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menupanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbatal;
    private javax.swing.JButton bcari;
    private javax.swing.JButton bdaftar;
    private javax.swing.JButton bdata;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bhome;
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton bubah;
    private javax.swing.JComboBox<String> cbagama;
    private javax.swing.JComboBox<String> cbpilihan1;
    private javax.swing.JComboBox<String> cbpilihan2;
    private javax.swing.JComboBox<String> cbpilihan3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpdaftar;
    private javax.swing.JPanel jpdata;
    private javax.swing.JPanel jpframe;
    private javax.swing.JPanel jphome;
    private javax.swing.JPanel jpisi;
    private javax.swing.JPanel jpmenu;
    private javax.swing.JRadioButton rblaki;
    private javax.swing.JRadioButton rbperempuan;
    private javax.swing.JTable tblmahasiswabaru;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtasalsekolah;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtkabkota;
    private javax.swing.JTextField txtkecamatan;
    private javax.swing.JTextField txtkewarganegaraan;
    private javax.swing.JTextField txtkodepos;
    private javax.swing.JTextField txtnamalengkap;
    private javax.swing.JTextField txtnik;
    private javax.swing.JTextField txtnotelepon;
    private javax.swing.JTextField txtprovinsi;
    private javax.swing.JTextField txttanggallahir;
    private javax.swing.JTextField txttempatlahir;
    // End of variables declaration//GEN-END:variables

    private void KoneksiDatabase() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            } catch (ClassNotFoundException cnf) {
            }
             try {
                 koneksi = DriverManager.getConnection("jdbc:mysql://localhost/penerimaanmahasiswabaru", "root", "");
                 JOptionPane.showMessageDialog(null, "Koneksi Database Berhasil");
            } catch (SQLException se) {
                 JOptionPane.showMessageDialog(null, "Koneksi Database Tidak Berhasil");
            } catch (Exception e) {
            }
    }

    private void TampilData() {
        //membuat tampilan model tabel
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("NIK");
            model.addColumn("Nama Lengkap");
            model.addColumn("Tempat Lahir");
            model.addColumn("Tanggal Lahir");
            model.addColumn("Jenis Kelamin");
            model.addColumn("Kewarganegaraan");
            model.addColumn("Agama");
            model.addColumn("No Telepon");
            model.addColumn("Email");
            model.addColumn("Asal Sekolah");
            model.addColumn("Alamat");
            model.addColumn("Kode Pos");
            model.addColumn("Provinsi");
            model.addColumn("Kab/Kota");
            model.addColumn("Kecamatan");
            model.addColumn("Pilihan Prodi 1");
            model.addColumn("Pilihan Prodi 2");
            model.addColumn("Pilihan Kelas");
            tblmahasiswabaru.setModel(model);

            //menampilkan data database kedalam tabel
            try {
                java.sql.Statement stat = koneksi.createStatement();
                ResultSet data = stat.executeQuery("SELECT * FROM mahasiswabaru");
                while (data.next()) {
                     model.addRow(new Object[]{
                        data.getString("NIK"),
                        data.getString("nama_lengkap"),
                        data.getString("tempat_lahir"),
                        data.getString("tanggal_lahir"),
                        data.getString("jenis_kelamin"),
                        data.getString("kewarganegaraan"),
                        data.getString("agama"),
                        data.getString("no_telepon"),
                        data.getString("email"),
                        data.getString("asal_sekolah"),
                        data.getString("alamat"),
                        data.getString("kode_pos"),
                        data.getString("provinsi"),
                        data.getString("kabkota"),
                        data.getString("kecamatan"),
                        data.getString("prodi_satu"),
                        data.getString("prodi_dua"),
                        data.getString("pilih_kelas")
                     });
                     tblmahasiswabaru.setModel(model);
                }
            } catch (Exception e) {
                System.err.println("Terjadi Kesalahan :" + e);
            }
    }
}
